name: Test Tutorials

on:
  push:
  pull_request:

jobs:
  test-tutorials:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tutorial:
          - tutorial-1-initialization
          - tutorial-2-implement-train
          - tutorial-3-encode-decode
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd ${{ matrix.tutorial }}
          pip install -r requirements.txt

      - name: Replace BPETokenizer.py with solution
        run: |
          cd ${{ matrix.tutorial }}/src
          mv solution_BPETokenizer.py BPETokenizer.py

      - name: Run pytest
        run: |
          cd ${{ matrix.tutorial }}
          pytest
